task_1-1
artem12207/TKI-142 pull request #1
Opened 2023-10-30 08:21 UTC by artem12207

Здравствуйте, это Барсегян Артём(ТКИ-142). Высылаю вам задание 1.1 , пока без документации

2023-11-03 06:10 UTC, MarinaPaley requested changes

2023-11-03 06:10 UTC, MarinaPaley commented on main.c
> +double getA(double x, double y)
необходимо добавить документацию

2023-11-03 06:10 UTC, MarinaPaley commented on main.c
> +double getB(double z)
Нет документации

2023-11-03 06:10 UTC, MarinaPaley commented on main.c
> +    printf("%s%lf", "b = ", b);
```
    printf("%s%lf\n", "a = ", getA(x, y));
    printf("%s%lf", "b = ", getB(z));
```

2023-12-14 06:47 UTC, artem12207 commented
#include <stduio.h> 
#include <math.h> 
 
/** 
* [id5159073|@brief] Возвращает результат функции a 
* [id153965260|@param] Параметр "x" для функуии a 
* [id153965260|@param] Параметр "y" для функуии a 
* [id153965260|@param] Параметр "z" для функуии a 
**/ 
double afunc(double x, double y, double z); 
 
/* 
* [id5159073|@brief] Возвращает результат функции a 
* [id153965260|@param] Параметр "x" для функуии a 
* [id153965260|@param] Параметр "y" для функуии a 
* [id153965260|@param] Параметр "z" для функуии a 
**/ 
double bfunc(double x, double y, double z); 
 
/* 
* [id5159073|@brief] Точка входа в программу 
* [id25798204|@return] Возвращает 0, если программа работает корректно, иначе не 0 
**/ 
int main() 
{ 
 const double x = 0.78; 
 const double y = 1.24; 
 const double z = 0.5; 
 double а = afunc(x, y, z); 
 double b = bfunc(x, y, z); 
 
 printf("a = %lf\n", a); 
 printf("b = %lf\n", b); 
 
 return 0; 
} 
 
double afunc(double x, double y, double z) 
{ 
 return (2 * pow(z,x)) / (sqrt((pow(y, x) * pow(cos(x + y), 2))) - 3 * z); 
} 
 
double bfunc(double x, double y, double z) 
{ 
 return x * exp(sqrt(z)) * cos((pow(x, 2)) / (y * z)); 
}

2023-12-18 16:50 UTC, MarinaPaley requested changes
Не понятно, что исправлено в коде

2024-03-02 11:22 UTC, merged